# Generated by Django 4.0.5 on 2022-06-14 00:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Menu',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=32, verbose_name='First Class Menu Title')),
                ('icon', models.CharField(blank=True, max_length=32, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Permission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=32, verbose_name='Title')),
                ('url', models.CharField(max_length=128, verbose_name='URL with RE')),
                ('name', models.CharField(max_length=32, unique=True, verbose_name='Alias of permission')),
                ('menu', models.ForeignKey(blank=True, help_text='Null means it is not a menu, non-null means it is a second class menu!', null=True, on_delete=django.db.models.deletion.CASCADE, to='rbac.menu', verbose_name='Belonging to the menu')),
                ('pid', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='parents', to='rbac.permission', verbose_name='Permissions of super Menu')),
            ],
        ),
        migrations.CreateModel(
            name='Role',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=32, verbose_name='Title')),
                ('permissions', models.ManyToManyField(blank=True, to='rbac.permission', verbose_name='Permission')),
            ],
        ),
    ]
